# These are supported funding model platforms

github: realrashid
patreon: realrashid
ko_fi: realrashid
issuehunt: realrashid
tidelift: "packagist/realrashid/sweet-alert"
custom: ['https://www.buymeacoffee.com/realrashid']
